### PR TITLE
ci(deps): configure Dependabot to read from GH packages

### PR DESCRIPTION
**Pull request by ebaron**
To handle cryostat-core updates, as done in: https://github.com/cryostatio/cryostat-reports/pull/76.

Related to: #14

### CODE REVIEW

**Comment by andrewazores** [comment]
I think this is currently failing because the CI runner probably doesn't have access to the required secret. I believe it would need to run as a `pull_request_target` event to read the secret token.

**Comment by ebaron** [comment]
> I think this is currently failing because the CI runner probably doesn't have access to the required secret. I believe it would need to run as a `pull_request_target` event to read the secret token.

I think so too. I ran into the same issue for -reports.

**Review by tthvo — APPROVED** [review]
Looks good! I think dependabot will be opening PR as upstream branch so this should pass as expected?

**Comment by andrewazores** [comment]
Yup, that's true. There is a new -core version that I just published a few minutes ago so we should see an update soon, hopefully.

**Pull request merged**
